### ISSUE TITLE
Steamcmd can't locate app build file

### ISSUE THREAD

**Issue by TeraV8** [buildalon/upload-steam#6]
When using the `app_build` parameter, steamcmd will fail with a file not found error regardless of whether the build file exists or not. This is due to the fact that the app build file path is passed to the program in quotation marks, and the quotation marks are part of the argument. Note that this issue isn't present on any of the other path-based arguments.

**Comment by StephenHodgson** [comment]
@TeraV8 thanks for reporting, can you give an example of a workflow file that breaks for you?

**Comment by TeraV8** [comment]
https://gist.github.com/TeraV8/310c489a34ecdc026307798272db05ee

**Comment by StephenHodgson** [comment]
Thanks, I'll look into this and fix it. Thanks for the PR, but I just need to do a quick build validation to make sure the changes work even with paths that contain whitespace characters.

**Comment by StephenHodgson** [comment]
I noticed that you use both windows and ubuntu, was it only the ubuntu runner that was failing?

**Comment by TeraV8** [comment]
Not sure, the windows job canceled as soon as the ubuntu build failed. It should be the same problem on both though, because the issue is the raw path string received by steamcmd contains the quotation marks

**Comment by StephenHodgson** [comment]
I def use this on my windows machines, but never tested fully on ubuntu. Can you add fail fast `false`  to your matrix to test it out?

[Edit]
Plz test unchanged action, and your edit

**Comment by StephenHodgson** [comment]
try this: 
```yaml
    uses: buildalon/upload-steam@development
      with:
        username: ${{ secrets.STEAM_USERNAME }}
        config: ${{ secrets.STEAM_CONFIG }}
        app_build: ${{ github.workspace }}/.github/workflows/build.vdf
```

plz let me know if it works for both your windows and ubuntu runs 🙏
